package fh_muenster.webservices;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.6.0
//
// Created by Quasar Development at 13/06/2016
//
//---------------------------------------------------



public interface AQLIServiceEvents
{
    public void Starting();
    public void Completed(AQLOperationResult result);
}
