package fh_muenster.webservices;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.6.0
//
// Created by Quasar Development at 13/06/2016
//
//---------------------------------------------------



import org.ksoap2.serialization.Marshal;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapSerializationEnvelope;
import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserException;
import org.xmlpull.v1.XmlSerializer;

import java.io.IOException;
import java.util.UUID;

/**
 * @author easywsdl.com
 */
public class AQLMarshalGuid implements Marshal
{
    /**
     *
     * @param parser
     * @param namespace
     * @param name
     * @param expected
     * @return
     * @throws IOException
     * @throws XmlPullParserException
     */
    public Object readInstance(XmlPullParser parser, String namespace, String name,PropertyInfo expected) throws IOException, XmlPullParserException
    {
        return UUID.fromString(parser.nextText());
    }

    /**
     *
     * @param cm
     */
    public void register(SoapSerializationEnvelope cm)
    {
        cm.addMapping(cm.xsd, "guid", UUID.class, this);
    }

    /**
     *
     * @param writer
     * @param obj
     * @throws IOException
     */
    public void writeInstance(XmlSerializer writer, Object obj) throws IOException
    {
        writer.text(obj.toString());
    }
}
