package fh_muenster.webservices;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.6.0
//
// Created by Quasar Development at 13/06/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

/**
 * @author easywsdl.com
 */
public class AQLNoSessionException extends Exception implements KvmSerializable
{

    
    public String message;

    public AQLNoSessionException ()
    {
    }

    /**
     *
     * @param paramObj
     * @param __envelope
     */
    public AQLNoSessionException (Object paramObj,AQLExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("message"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.message = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.message = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    /**
     *
     * @param propertyIndex
     * @return
     */
    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.message!=null?this.message:SoapPrimitive.NullSkip;
        }
        return null;
    }

    /**
     *
     * @return
     */
    @Override
    public int getPropertyCount() {
        return 1;
    }

    /**
     *
     * @param propertyIndex
     * @param arg1
     * @param info
     */
    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "message";
            info.namespace= "";
        }
    }

    /**
     *
     * @param arg0
     * @param arg1
     */
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

}
